db:
  username: ${username.value:postgres}
  password: qaZwsX.1001
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa

logging:
  level:
    root: INFO
    com.dmdev.spring.database.pool: INFO
    org.springframework.jdbc.core: DEBUG
  file:
    name: dmdev.log
    path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qaZwsX.1001
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      batch_size: 50
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 170149324429-nuodkvleun6j9ngq8e5ut84o99jijv7t.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: https://localhost:8080/login/oauth2/code/google
            scope: openid, email, profile